full_PFC_S_BT = filter_one_variable(full_PFC_S_BT);
full_PFC_S_RC = filter_one_variable(full_PFC_S_RC);
full_PFC_S_GC = filter_one_variable(full_PFC_S_GC);
full_PFC_S_YT = filter_one_variable(full_PFC_S_YT);
full_PFC_D_BT = filter_one_variable(full_PFC_D_BT);
full_PFC_D_RC = filter_one_variable(full_PFC_D_RC);
full_PFC_D_GC = filter_one_variable(full_PFC_D_GC);
full_PFC_D_YT = filter_one_variable(full_PFC_D_YT);
full_VA_shape = filter_one_variable(full_VA_shape);
full_VA_ori = filter_one_variable(full_VA_ori);
full_MD_shape = filter_one_variable(full_MD_shape);
full_MD_ori = filter_one_variable(full_MD_ori);
full_PFC_remote_shape = filter_one_variable(full_PFC_remote_shape);
full_PFC_remote_ori = filter_one_variable(full_PFC_remote_ori);
full_VA_shape_num = filter_one_variable(full_VA_shape_num);
full_MD_shape_num = filter_one_variable(full_MD_shape_num);
full_PFC_remote_shape_num = filter_one_variable(full_PFC_remote_shape_num);

save("spike_time_health1", ...
    'full_PFC_S_BT', ...
    'full_PFC_S_RC', ...
    'full_PFC_S_GC', ...
    'full_PFC_S_YT', ...
    'full_PFC_D_BT', ...
    'full_PFC_D_RC', ...
    'full_PFC_D_GC', ...
    'full_PFC_D_YT', ...
    'full_VA_shape', ...
    'full_VA_ori', ...
    'full_MD_shape', ...
    'full_MD_ori', ...
    'full_PFC_remote_shape', ...
    'full_PFC_remote_ori', ...
    'full_VA_shape_num', ...
    'full_MD_shape_num', ...
    'full_PFC_remote_shape_num', ...
    '-v7.3');
%%

function filtered_data = filter_one_variable(full_variable, threshold)
% full_variable: varialbe that need to be filtered
% thresh: time threshold
    if nargin < 2
        threshold = 450000;
    end
    
    filtered_data = cell(length(full_variable), 1);
    for i = 1:length(full_variable)
        one_trial_data = full_variable{i};
        filtered_data{i} = one_trial_data(one_trial_data(:, 2) < threshold, :);
    end
end